In [ ]:
--- CREATE TABLE agentes --
drop table IF EXISTS e2014.agentes;
CREATE TABLE e2014.agentes(
  id integer NOT NULL DEFAULT nextval('id'),
	cod_agente	varchar,
	tipo		varchar,
	cnpj		varchar,
	sigla_uf	varchar,
	sigla_ue	varchar,
	numero_partido	varchar,
	sigla_partido	varchar,
	nome_agente	varchar,
	cod_candidatura	varchar,
	nome_candidatura	varchar,
	cargo           varchar,
	apto            varchar,
	codigo_cargo    varchar,
	grupo           varchar,
	nome_grupo      varchar
);

CREATE  INDEX cnpj_idx ON e2014.agentes (cnpj);

CREATE  INDEX nome_agente_idx ON e2014.agentes (nome_agente);

In [ ]:
--- INSERT agentes from receitas_comites --
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente,
	cod_candidatura,
	nome_candidatura,
	cargo 
  )
(
SELECT 
	'' as cod_agente,
	'CF',
	e2014.get_cpf_cnpj(cnpj_prestador_conta) as cnpj,
	max(uf) as sigla_uf,
	max(uf) as sigla_ue,
	'' as numero_partido,
	max(sigla_partido) as sigla_partido,
	max(tipo_comite) as nome_agente,
	'' as cod_candidatura,
	'' as nome_candidatura,
	'' as cargo
FROM 
  tse2014.receitas_comites_2014 as rc
where
  e2014.get_cpf_cnpj(cnpj_prestador_conta) not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cnpj_prestador_conta
);

In [ ]:
--- INSERT agentes from despesas_comites --
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente,
	cod_candidatura,
	nome_candidatura,
	cargo 
)
(
SELECT 
	'' as cod_agente,
	'CF',
	e2014.get_cpf_cnpj(cnpj_prestador_conta) as cnpj,
	max(uf) as sigla_uf,
	max(uf) as sigla_ue,
	'' as numero_partido,
	max(sigla_partido) as sigla_partido,
	max(tipo_comite) as nome_agente,
	'' as cod_candidatura,
	'' as nome_candidatura,
	'' as cargo
FROM 
  tse2014.despesas_comites_2014
where
  e2014.get_cpf_cnpj(cnpj_prestador_conta)  not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cnpj_prestador_conta
);

In [ ]:
--- INSERT agentes from receitas_partidos --
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente,
	cod_candidatura,
	nome_candidatura,
	cargo 
  )
(
SELECT 
	'' as cod_agente,
	'DE',
	e2014.get_cpf_cnpj(cnpj_prestador_conta) as cnpj,
	max(uf) as sigla_uf,
	max(uf) as sigla_ue,
	'' as numero_partido,
	max(sigla_partido),
	max(tipo_diretorio),
	'',
	'',
	''
FROM 
  tse2014.receitas_partidos_2014
where
  e2014.get_cpf_cnpj(cnpj_prestador_conta)  not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cnpj_prestador_conta
);

In [ ]:
--- INSERT agentes from despesas_partidos --
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente,
	cod_candidatura,
	nome_candidatura,
	cargo 
  )
(
SELECT 
	'' as cod_agente,
	'DE',
	e2014.get_cpf_cnpj(cnpj_prestador_conta) as cnpj,
	max(uf) as sigla_uf,
	max(uf) as sigla_ue,
	'' as numero_partido,
	max(sigla_partido),
	max(tipo_diretorio),
	'',
	'',
	''
FROM 
  tse2014.despesas_partidos_2014
where
  e2014.get_cpf_cnpj(cnpj_prestador_conta)  not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cnpj_prestador_conta
);

In [ ]:
--- INSERT agentes from receitas_candidatos --
--"9492800"
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente
)
(
SELECT 
	'' as cod_agente,
	'CC' as tipo,
	e2014.get_cpf_cnpj(cpf_cnpj_doador) as cnpj,
	max(sigla_ue_doador) as sigla_uf,
	max(sigla_ue_doador) as sigla_ue,
        max(numero_partido_doador) as numero_partido,
        '' as sigla_partido,
	max(nome_doador_receita_federal) as nome_agente
FROM  	
  tse2014.receitas_candidatos_2014
where
 cod_setor_economico_doador = '9492800'
 and
 e2014.get_cpf_cnpj(cpf_cnpj_doador)  not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cpf_cnpj_doador
);

In [ ]:
--- INSERT agentes from receitas_comites --
--"9492800"
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente
)
(
SELECT 
	'' as cod_agente,
	'CC' as tipo,
	e2014.get_cpf_cnpj(cpf_cnpj_doador) as cnpj,
	max(sigla_ue_doador) as sigla_uf,
	max(sigla_ue_doador) as sigla_ue,
        max(numero_partido_doador) as numero_partido,
        '' as sigla_partido,
	max(nome_doador_receita_federal) as nome_agente
FROM  	
  tse2014.receitas_comites_2014
where
  cod_setor_economico_doador = '9492800'
  and
  e2014.get_cpf_cnpj(cpf_cnpj_doador)  not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cpf_cnpj_doador
);

In [ ]:
-- INSERT agentes from receitas_partidos --
-- "9492800"
INSERT INTO e2014.agentes (
	cod_agente,
	tipo,
	cnpj,
	sigla_uf,
	sigla_ue,
	numero_partido,
	sigla_partido,
	nome_agente
)
(
SELECT 
	'' as cod_agente,
	'CC' as tipo,
	e2014.get_cpf_cnpj(cpf_cnpj_doador) as cnpj,
	max(sigla_ue_doador) as sigla_uf,
	max(sigla_ue_doador) as sigla_ue,
        max(numero_partido_doador) as numero_partido,
        '' as sigla_partido,
	max(nome_doador_receita_federal) as nome_agente
FROM  	
  tse2014.receitas_partidos_2014
where
  cod_setor_economico_doador = '9492800'
  and
  e2014.get_cpf_cnpj(cpf_cnpj_doador)  not in(select e2014.agentes.cnpj from e2014.agentes)
group by
  cpf_cnpj_doador
);

In [ ]:
--------------------------------------------
-- AJUSTA NUMERO_PARTIDO EM CF
with partidos as
(
  select
   numero,
   sigla
  from 
    e2014.partidos
)
UPDATE e2014.agentes as a
set 
    numero_partido = p.numero
from 
    partidos as p
where
    tipo = 'CF'
    and
    p.sigla = a.sigla_partido 
;

-- AJUSTA NUMERO_PARTIDO EM DE
with partidos as
(
  select
   numero,
   sigla
  from 
    e2014.partidos
)
UPDATE e2014.agentes as a
set 
    numero_partido = p.numero
from 
    partidos as p
where
    tipo = 'DE'
    and
    p.sigla = a.sigla_partido 
;

In [ ]:
-- AJUSTA SIGLA_PARTIDO EM CF
with partidos as
(
  select
   numero,
   sigla
  from 
   e2014.partidos
)
UPDATE e2014.agentes as a
set 
    sigla_partido = p.sigla
from 
    partidos as p
where
    tipo in ('CF', 'CC')
    and
    sigla_partido = ''
    and
    p.numero = a.numero_partido 
;


-- AJUSTA SIGLA_PARTIDO EM DE
with partidos as
(
  select
   numero,
   sigla
  from 
   e2014.partidos 
)
UPDATE e2014.agentes as a
set 
    sigla_partido = p.sigla
from 
    partidos as p
where
    tipo = 'DE'
    and
    sigla_partido = ''
    and
    p.numero = a.numero_partido 
;

In [ ]:
-- ASSOCIA DADOS CANDIDATURA A CC
with candidaturas as
(
  select 
    cnpj_candidatura,
    sigla_uf,
    sigla_ue,
    numero_partido,
    sigla_partido,
    cod_candidatura,
    tipo_candidatura,
    nome_candidato,
    nome_candidatura,
    descricao_cargo,
    codigo_cargo,
    apto
  from
    e2014.candidaturas as c
) 
UPDATE e2014.agentes as a
  set 
    cod_agente = c.cod_candidatura,
    sigla_uf = c.sigla_uf,
    sigla_ue = c.sigla_ue,
    numero_partido = c.numero_partido,
    sigla_partido  = c.sigla_partido,
    cod_candidatura = c.cod_candidatura,
    nome_candidatura = c.nome_candidatura,
    cargo = c.descricao_cargo,
    codigo_cargo = c.codigo_cargo,
    apto         = c.apto,
    grupo        = c.tipo_candidatura,
    nome_grupo   = c.nome_candidatura
from
  candidaturas as c
where
    a.tipo = 'CC'
    and
    c.cnpj_candidatura like a.cnpj
;

In [ ]:
/*--
FAZER BUSCA PELO NOME PARA OS 'CC' QUE FICARAM SEM COD-CANDIDATURA
PELO NOME
--*/ 


with candidaturas as
(
  select 
    c.cnpj_candidatura,
    c.sigla_uf,
    c.sigla_ue,
    c.numero_partido,
    c.sigla_partido,
    c.cod_candidatura,
    c.tipo_candidatura,
    c.nome_candidato,
    c.nome_candidatura,
    c.descricao_cargo,
    c.codigo_cargo
  from
    e2014.candidaturas as c
)   
update e2014.agentes as a
set 
    cod_agente = c.cod_candidatura,
    sigla_uf = c.sigla_uf,
    sigla_ue = c.sigla_ue,
    numero_partido = c.numero_partido,
    sigla_partido  = c.sigla_partido,
    cod_candidatura = c.cod_candidatura,
    nome_candidatura = c.nome_candidatura,
    cargo = c.descricao_cargo,
    codigo_cargo = c.codigo_cargo,
    grupo        = c.tipo_candidatura,
    nome_grupo   = c.nome_candidatura,
    nome_agente  = c.nome_candidatura
from candidaturas as c
where
    a.nome_agente like '%'||trim(c.nome_candidato)||'%'
    --is_nome_igual(c.nome_candidato,a.nome_agente)
; 



-- ajusta cod_agente e nome agente, grupo e nome_grupo se CF 
update e2014.agentes as a
set cod_agente = 'AP'||sigla_ue||numero_partido,
    nome_agente = 'Comitê Financeiro ('||sigla_partido||'/'||sigla_ue||')',
    grupo = 'AP',
    nome_grupo = 'Agente Partidário ('||sigla_partido||'/'||sigla_ue||')'
where tipo  = 'CF'
;
  
-- ajusta cod_agente e nome agente, grupo e nome_grupo se DE
update e2014.agentes as a
set cod_agente = 'AP'||sigla_ue||numero_partido,
    nome_agente = 'Direção Partidária ('||sigla_partido||'/'||sigla_ue||')',
    grupo = 'AP',
    nome_grupo = 'Agente Partidário ('||sigla_partido||'/'||sigla_ue||')'
where tipo = 'DE'
;

In [ ]:
----------------   IMPRTANTE -----------------------------------------------------------------------------
-- ACERTAR SIGLA UF PARA OS CC cod_agente = '' A PARTIR DE SIGLA UE --- REVISAR A GERACAO DE SIGLA US EM TODAS AS TABELAS
-----------------------------------------------------------------------------------------------------------
with municipios as
( select sigla_uf, sigla_ue, nome_ue from e2014.municipios )
update e2014.agentes as a
set sigla_uf = m.sigla_uf
from municipios as m
where m.sigla_ue = a.sigla_ue
;

-- estabelece cod_agente e nome agente, grupo e nome_grupo se CC 
with agentes as (
select cnpj, grupo,sigla_uf,sigla_partido,numero_partido from e2014.agentes
) 
update e2014.agentes as aj
set 
    cod_agente = 'AP'||a.sigla_uf||a.numero_partido,
    nome_agente = 'Comitê Financeiro ('||a.sigla_partido||'/'||a.sigla_uf||')',
    grupo = 'AP',
    nome_grupo =  'Agente Partidário ('||a.sigla_partido||'/'||a.sigla_uf||')'
from agentes as a
where aj.tipo = 'CC' 
and aj.grupo = ''
and aj.sigla_uf <> '#NULO'
and aj.cnpj = '%'||a.cnpj||'%'
;

In [ ]:
-- select e2014.create_populate_agentes();

-- select e2014.ajusta_agentes_sem_partido_2014();

/*-- TESTES

select count(*) from e2014.agentes

select count(*) from e2014.agentes
where cod_agente = ''

select * from e2014.agentes
where cod_agente = ''

select * from e2014.agentes as a
where
    a.cod_agente = ''
    and
    a.tipo = 'CC'
;

select tipo, grupo, count(*) from e2014.agentes group by tipo, grupo;

select * from e2014.agentes where tipo = 'CC' and grupo = 'CA'

select * from e2014.agentes where tipo = 'CC' and grupo = 'CF'


select * from e2014.agentes
where grupo = 'CA'
order by cargo


select * from e2014.agentes
where tipo = 'CF'
order by cod_agente

select * from e2014.agentes
where tipo = 'DE'
order by cod_agente

select cod_agente, nome_agente from e2014.agentes
where tipo = 'CF'
group by cod_agente, nome_agente 
order by cod_agente, nome_agente 

select cod_agente, nome_grupo from e2014.agentes
where tipo = 'CF'
group by cod_agente, nome_grupo
order by cod_agente, nome_grupo

select cod_agente, nome_agente from e2014.agentes
where tipo = 'DE'
group by cod_agente, nome_agente 
order by cod_agente, nome_agente 

select cod_agente, nome_grupo from e2014.agentes
where tipo = 'DE'

select count(*) from e2014.agentes
where cod_agente = ''
group by cod_agente, nome_grupo
order by cod_agente, nome_grupo

select * from e2014.agentes
where tipo = 'DE' 
order by cod_agente 

select * from e2014.agentes
where tipo = 'CC'
order by cod_agente

select * from e2014.agentes
where tipo = 'CC'
and cod_agente = ''
and
nome_agente like '%ELEICAO%'
order by nome_agente 

select * from e2014.agentes
where tipo = 'CC'
and cod_agente like 'CA%'



-- select ajusta_agentes_partido_candidatura_2014();

-- POSSIVEIS AGENTES PARTIDARIOS SEM  sigla_uf e sigla_partido
-- select * from e2014.agentes where sigla_uf ='' and nome_agente not like '%ELEICAO%';


-- POSSIVEIS AGENTES DE CANDIDATURA SEM (cod_candidatura, sigla_uf, sigla_partido)
-- select * from e2014.agentes where sigla_uf ='' and nome_agente  like '%ELEICAO%';


   select * from e2014.agentes as a, candidaturas_2014 as c
   where is_nome_igual(c.nome_candidato, a.nome_agente)

   select * from e2014.agentes as a, candidaturas_2014 as c
   where is_nome_igual(c.nome_candidato, a.nome_agente)



select * from candidaturas_2014 as c, e2014.agentes as a
where a.nome_agente like concat('%',c.nome_candidatura,'%')


 
   select * from e2014.agentes as a left join  candidaturas_2014 as c
   on  a.nome_agente similar to '%'||c.nome_candidato||'%'



   select * from e2014.agentes where codigo_cargo = '3' order by cod_candidatura;

-- CC com para a mesma candidatura
select * from e2014.agentes as ou
where (select count(*) from e2014.agentes as inr
where inr.cod_candidatura = ou.cod_candidatura) > 1 and codigo_cargo <> ''
order by codigo_cargo, cod_candidatura;

select * from candidaturas_2014 where codigo_cargo = '1';

select * from candidaturas_2014 where codigo_cargo = '3' order by apto
;
select * from candidaturas_2014 where sequencial_candidato = '90000000316';

select * from tse2014.votacao_candidato_munzona_2014 where sequencial_candidato = '90000000316';

--*/